### ISSUE TITLE
Nevermind

### ISSUE THREAD

**Issue by vwarg** [jsonfry/uk.co.jasonfry.android.tools#1]
I have no idea if this is an error on my part, if I'm expecting something this project doesn't do, or if it's an error somewhere in your code, but I cannot get the vertical scrolling to work at all. The horizontal scrolling works flawlessly, however the vertical scroll does not scroll vertically. Instead it scrolls horizontally if I move my finger even the slightest bit to the side while trying to scroll vertically. I believe it has something to do with the 'mSendingDummyMotionEvent'-variable, which seems to always be set to false.

Please help me find a solution.
I'm using the latest version which as of this writing is commit 93c00f5e21ac094edefe.

Thanks in advance,
vwarg

---EDIT---
I'm stupid. I had overridden the onTouchEvent-method in my child-class, and only had it return false. So yes, your code works perfectly now.

**Comment by vwarg** [comment]
As seen in the edit, I managed to work it out.

**Comment by jsonfry** [comment]
No worries!
