### ISSUE TITLE
pagecontrol is not refreshed

### ISSUE THREAD

**Issue by Georges67** [jsonfry/uk.co.jasonfry.android.tools#4]
Hello,
I'm currently using your cool library that works well.
But when I add dynamically a new view, this one is correctly displayed, but the pagecontrol is not refresh ; it still displays 2 bubbles while there is 3 views above.

Could you tell me how to refresh the pagecontrol? 
Thanks,

**Comment by jsonfry** [comment]
Currently you'd have to reinitialise the page control, but I think someone has a fork that has a better solution than that, I've not had a look at it yet beyond the commit logs, if it's nice I'll be bringing it back into my repo.
